# Generated by Django 4.1.6 on 2023-02-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_secretaria_prefeitura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefeitura',
            name='nome',
            field=models.CharField(max_length=30, null=True, verbose_name='Nome da Prefeitura'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='nome',
            field=models.CharField(max_length=40, null=True, verbose_name='Nome da Secretária'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='sigla',
            field=models.CharField(max_length=7, null=True, verbose_name='Sigla da Secretária'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='uf',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='uf'),
        ),
    ]
