# Generated by Django 4.1.6 on 2023-02-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_prefeitura_nome_alter_secretaria_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='nome',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Nome da Secretária'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='sigla',
            field=models.CharField(max_length=7, null=True, unique=True, verbose_name='Sigla da Secretária'),
        ),
    ]
