# Generated by Django 4.1.6 on 2023-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_secretaria_nome_alter_secretaria_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='status',
            field=models.CharField(choices=[('ativo', 'ativo'), ('inativo', 'inativo')], max_length=10, null=True, verbose_name='Status'),
        ),
    ]
