# Generated by Django 4.1.6 on 2023-02-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_secretaria_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=10, null=True, verbose_name='Status'),
        ),
    ]
