# Generated by Django 4.1.6 on 2023-02-14 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_secretaria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='cep'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cns',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Cns'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='ctps',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Ctps número:'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='ctpsserie',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='ctpsuf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='pis',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='PIS'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='rg',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Rg'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='prefeitura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.prefeitura', verbose_name='Prefeitura'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.secretaria', verbose_name='Secretária'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=10, null=True, verbose_name='Status'),
        ),
    ]
