# Generated by Django 4.1.6 on 2023-02-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_colaborador_cep_alter_colaborador_cns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='estadocivil',
            field=models.CharField(blank=True, choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo')], max_length=15, null=True, verbose_name='Estadocivil'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nascimento',
            field=models.DateField(blank=True, max_length=9, null=True, verbose_name='Nascimento'),
        ),
    ]
