# Generated by Django 4.1.6 on 2023-02-15 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0016_alter_colaborador_email_alter_colaborador_matricula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, null=True, unique=True, verbose_name='Nome')),
                ('tipo', models.DateField(blank=True, max_length=9, null=True, verbose_name='Nascimento')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=10, null=True, verbose_name='Status')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Anexo')),
                ('criadopor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.prefeitura', verbose_name='Prefeitura')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.secretaria', verbose_name='Secretária')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.setor', verbose_name='Setor')),
            ],
        ),
    ]
