# Generated by Django 4.1.6 on 2023-02-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.DateField(blank=True, max_length=9, null=True, verbose_name='Tipo'),
        ),
    ]
