# Generated by Django 4.1.6 on 2023-02-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_documento_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='criadopor',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='prefeitura',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='secretaria',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tipo',
        ),
    ]
