# Generated by Django 4.1.6 on 2023-02-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.DateField(choices=[('processo', 'Processo'), ('requerimeto', 'requerimento'), ('ata', 'Ata'), ('ci', 'Ci'), ('documento', 'Documento')], max_length=15, null=True, verbose_name='Tipo'),
        ),
    ]
