# Generated by Django 4.1.6 on 2023-02-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
