# Generated by Django 4.1.6 on 2023-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexo/', verbose_name='Anexo'),
        ),
    ]
