# Generated by Django 4.1.6 on 2023-02-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_alter_documento_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='ano',
            field=models.CharField(max_length=15, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='numeracao',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Numeração'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('processo', 'Processo'), ('requerimeto', 'Requerimento'), ('ata', 'Ata'), ('ci', 'Ci'), ('documento', 'Documento')], max_length=15, null=True, verbose_name='Tipo'),
        ),
    ]
