# Generated by Django 4.1.6 on 2023-02-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_alter_documento_ano_alter_documento_numeracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('recebido', 'Recebito')], max_length=10, null=True, verbose_name='Status'),
        ),
    ]
