# Generated by Django 4.1.6 on 2023-02-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_alter_documento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_recebimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
