# Generated by Django 4.1.6 on 2023-02-20 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0031_documento_data_recebimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_recebidos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='origem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
