# Generated by Django 4.1.6 on 2023-02-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_documento_destino_documento_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='date_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
