# Generated by Django 4.1.6 on 2023-02-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_alter_historico_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='data_saida',
            field=models.DateTimeField(),
        ),
    ]
