# Generated by Django 4.1.6 on 2023-02-22 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0038_alter_historico_data_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='criadopor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historico',
            name='data_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
