# Generated by Django 4.1.6 on 2023-02-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_historico_criadopor_alter_historico_data_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_criacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
