# Generated by Django 4.1.6 on 2023-02-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_foto_perfil_matricula_alter_perfil_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(upload_to='userfoto/', verbose_name='Sua Foto'),
        ),
    ]
