# Generated by Django 4.1.6 on 2023-02-22 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_alter_historico_data_saida'),
        ('usuarios', '0005_alter_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='prefeitura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.prefeitura', verbose_name='Prefeitura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='secretaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.secretaria', verbose_name='Secretária'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.setor', verbose_name='Setor'),
            preserve_default=False,
        ),
    ]
